# Write your MySQL query statement below
SELECT R.score ,COUNT(R2.SCORE) as `rank` FROM SCORES R,
(SELECT DISTINCT SCORE FROM SCORES)  R2
WHERE R.SCORE<=R2.SCORE 
GROUP BY R.ID 
ORDER BY R.SCORE DESC;